import sqlite3
import pandas as pd
import time

CSVForm = pd.read_csv("DATA/SMILESEnthalpyLookUpAPPEND.csv")
conn = sqlite3.connect("DATA/EnthalpyTables.db")
cursor = conn.cursor()

target_smiles = [ # test data generated by google gemini and edited, not concialzed but good for testing because will need to sreaching for nonexisting items
    "O=C=O",  # Carbon dioxide
    "N#N",  # Nitrogen gas
    "CO",  # Methanol
    "CCO",  # Ethanol
    "CC(=O)C",  # Acetone

    # Standard combustion & atmospheric gases
    "O=O",  # Oxygen gas
    "[C-]#[O+]",  # Carbon monoxide
    "O",  # Water
    "N",  # Ammonia
    "C",  # Methane

    # Alkanes (straight and branched)
    "CC",  # Ethane
    "CCC",  # Propane
    "CCCC",  # Butane
    "CCCCC",  # Pentane
    "CC(C)C",  # Isobutane
    "CC(C)(C)C",  # Neopentane

    # Alkenes & Alkynes
    "C=C",  # Ethene
    "C=CC",  # Propene
    "C=CCC",  # 1-Butene
    "C#C",  # Ethyne (Acetylene)
    "C#CC",  # Propyne

    # Alcohols & Ethers
    "CCCO",  # 1-Propanol
    "CC(C)O",  # Isopropanol (2-Propanol)
    "CCCCO",  # 1-Butanol
    "COC",  # Dimethyl ether
    "CCOCC",  # Diethyl ether
    "COCC",  # Ethyl methyl ether

    # Aldehydes & Ketones
    "C=O",  # Formaldehyde
    "CC=O",  # Acetaldehyde
    "CCC=O",  # Propanal
    "CCC(=O)C",  # Butanone

    # Carboxylic Acids & Esters
    "O=CO",  # Formic acid
    "CC(=O)O",  # Acetic acid
    "CCC(=O)O",  # Propanoic acid
    "COC(=O)C",  # Methyl acetate
    "CCOC(=O)C",  # Ethyl acetate

    # Aromatics & Cyclics
    "c1ccccc1",  # Benzene
    "Cc1ccccc1",  # Toluene
    "c1ccncc1",  # Pyridine
    "c1ccoc1",  # Furan
    "C1CCCCC1",  # Cyclohexane
    "C1CCCC1",  # Cyclopentane
    "C1CC1",  # Cyclopropane

    # Nitrogen-containing organics
    "CN",  # Methylamine
    "CCN",  # Ethylamine
    "C(#N)C",  # Acetonitrile
    "C(=O)(N)C",  # Acetamide

    # Sulfur/Halogen-containing (small representatives)
    "CS",  # Methanethiol
    "CCl",  # Chloromethane
    "FC(F)(F)F"  # Tetrafluoromethane
]

def timer(func):
    def wrapper(*args, **kwargs):
        t1 = time.time()
        result = func(*args, **kwargs)
        t2 = time.time()
        print(f'Function {func.__name__!r} executed in {(t2-t1):.4f}s')
        return result
    return wrapper

@timer
def speedtestCSV(querys):
    # Exact match lookup
    result = []
    for query in querys:
        result.append(CSVForm[CSVForm["SMILES"] == query])
    #print(result)

@timer
def speedtestDB(querys):
    result = []
    for query in querys:
        # Query a specific table using a parameterized query (?)
        cursor.execute("SELECT * FROM Radical_0 WHERE SMILES = ?", (query,))
        result.append(cursor.fetchall())
    #print("db :",result)

speedtestCSV(target_smiles)
speedtestDB(target_smiles)